spring.application.name=affordBackend

testserver.base-url=http://4.224.186.213/evaluation-service


testserver.access-code=xxkJnk
testserver.roll-no=2301920100363
testserver.email=cse23304@glbitm.ac.in
testserver.name=Vivek
testserver.github-username=vivan-1045
testserver.mobile-no=8383991315

testserver.client-id=31d9ce6c-1130-4dc6-b2ae-fd7476234b49
testserver.client-secret=WANHNZYWYeFYBJAT
